# Generated by Django 6.0.4 on 2026-04-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('round_robin', 'Round Robin'), ('hybrid', 'Hybrid'), ('group_knockout', 'Group Knockout')], default='round_robin', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.CharField(blank=True, choices=[('A', 'Group A'), ('B', 'Group B')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('round_robin', 'Round Robin'), ('group', 'Group Stage'), ('semifinal', 'Semifinal'), ('final', 'Final'), ('third_place', '3rd Place Match')], default='round_robin', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('event', 'team_a', 'team_b', 'stage')},
        ),
    ]
