# Generated by Django 6.0.4 on 2026-04-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eventresult'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventresult',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventresult',
            name='division',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], default='men', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='division',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], default='men', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='eventresult',
            unique_together={('event', 'department', 'division'), ('event', 'position', 'division')},
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('event', 'team_a', 'team_b', 'stage', 'division')},
        ),
    ]
