# Generated by Django 4.2.7 on 2026-04-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_division_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_a',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_b',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
