# Generated by Django 4.2.7 on 2026-04-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_decimal_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload department logo (PNG or JPG recommended)', null=True, upload_to='department_logos/'),
        ),
    ]
