# Generated by Django 4.2.30 on 2026-05-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_department_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='division_type',
            field=models.CharField(choices=[('men', 'Men Only'), ('women', 'Women Only'), ('both', 'Both Divisions')], default='both', help_text='Which division(s) this event is played in.', max_length=10),
        ),
    ]
