# Generated by Django 4.2.30 on 2026-05-01 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_event_division_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_categories',
            field=models.BooleanField(default=False, help_text='Enable for sports with multiple categories (e.g. Badminton: Singles Men, Doubles Men, Singles Women, Doubles Women, Mixed). When enabled, matches are generated per category instead of per division.'),
        ),
        migrations.AlterField(
            model_name='match',
            name='division',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('mixed', 'Mixed')], default='men', max_length=10),
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category_type', models.CharField(choices=[('singles_men', 'Singles Men'), ('doubles_men', 'Doubles Men'), ('singles_women', 'Singles Women'), ('doubles_women', 'Doubles Women'), ('mixed', 'Mixed Doubles')], max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.event')),
            ],
            options={
                'ordering': ['category_type'],
                'unique_together': {('event', 'category_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='match',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='core.eventcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('event', 'team_a', 'team_b', 'stage', 'division', 'category')},
        ),
    ]
