# Generated by Django 4.2.30 on 2026-05-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fix_eventcategory_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='has_categories',
            field=models.BooleanField(default=False, help_text='Enable for sports with multiple categories (e.g. Badminton: Singles, Doubles, Mixed). When enabled, standings are shown per category + division.'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='category_type',
            field=models.CharField(choices=[('singles', 'Singles'), ('doubles', 'Doubles'), ('mixed', 'Mixed')], max_length=20),
        ),
    ]
