# Generated by Django 4.2.30 on 2026-05-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_simplify_category_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
