# Generated by Django 4.2.30 on 2026-05-04 00:28

from django.db import migrations, models


def convert_round_robin_to_hybrid(apps, schema_editor):
    """Convert any existing round_robin events to hybrid before removing the choice."""
    Event = apps.get_model('core', 'Event')
    Event.objects.filter(format='round_robin').update(format='hybrid')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_score_updated_at'),
    ]

    operations = [
        # First convert any existing round_robin events to hybrid
        migrations.RunPython(
            convert_round_robin_to_hybrid,
            reverse_code=migrations.RunPython.noop,
        ),
        # Then update the field choices and default
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('group_knockout', 'Group Knockout')], default='hybrid', max_length=20),
        ),
    ]
