# Generated by Django 4.2.30 on 2026-05-05 12:59

from django.db import migrations, models


def convert_student_to_organizer(apps, schema_editor):
    """Convert any existing student role accounts to organizer."""
    UserProfile = apps.get_model('core', 'UserProfile')
    UserProfile.objects.filter(role='student').update(role='organizer')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_round_robin_format'),
    ]

    operations = [
        # First convert any existing student records
        migrations.RunPython(
            convert_student_to_organizer,
            reverse_code=migrations.RunPython.noop,
        ),
        # Then update the field choices and default
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('organizer', 'Organizer')], default='organizer', max_length=20),
        ),
    ]
