from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('', views.dashboard_view, name='home'),
    path('departments/', views.department_list, name='department_list'),
    path('departments/add/', views.department_create, name='department_create'),
    path('departments/<int:pk>/edit/', views.department_update, name='department_update'),
    path('departments/<int:pk>/delete/', views.department_delete, name='department_delete'),
    path('departments/<int:pk>/sync/', views.department_sync, name='department_sync'),
    path('events/', views.event_list, name='event_list'),
    path('events/create/', views.event_create, name='event_create'),
    path('events/<int:pk>/edit/', views.event_update, name='event_update'),
    path('events/<int:pk>/delete/', views.event_delete, name='event_delete'),
    path('schedule/', views.match_list, name='match_list'),
    path('schedule/create/', views.match_create, name='match_create'),
    path('schedule/<int:pk>/edit/', views.match_update, name='match_update'),
    path('schedule/<int:pk>/delete/', views.match_delete, name='match_delete'),
    path('results/', views.results_list, name='results_list'),
    path('results/<int:pk>/score/', views.score_update, name='score_update'),
    path('results/<int:pk>/sets/', views.set_score_update, name='set_score_update'),
    path('leaderboard/', views.leaderboard_view, name='leaderboard'),
    path('overall-leaderboard/', views.overall_leaderboard_view, name='overall_leaderboard'),
    path('organizers/', views.organizer_list, name='organizer_list'),
    path('organizers/create/', views.organizer_create, name='organizer_create'),
    path('organizers/<int:pk>/edit/', views.organizer_edit, name='organizer_edit'),
    path('organizers/<int:pk>/delete/', views.organizer_delete, name='organizer_delete'),
    path('seasons/', views.season_list, name='season_list'),
    path('seasons/create/', views.season_create, name='season_create'),
    path('seasons/<int:pk>/edit/', views.season_update, name='season_update'),
    path('seasons/<int:pk>/delete/', views.season_delete, name='season_delete'),
    path('seasons/<int:pk>/switch/', views.season_switch, name='season_switch'),
    path('api/latest-result/', views.latest_result_api, name='latest_result_api'),
]
